version: "2"

services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    volumes:
      - /var/local/docker-volumes/redis:/bitnami/redis/data
    network_mode: host
    restart: unless-stopped
  redis-insight:
    image: "redislabs/redisinsight:latest"
    ports: 
      - "8001:8001"
    volumes:
      - /var/local/docker-volumes/redis-insight:/db
    restart: unless-stopped
  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: unless-stopped
    ports:
      - 3000:3000
  mongodb:
    profiles:
      - db
    image: mongodb/mongodb-community-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - /var/local/docker-volumes/mongo:/data/db
