version: "2"

services:
  redis:
    profiles:
      - services
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - 6379:6379
    volumes:
      - ./db/redis:/bitnami/redis/data
    network_mode: host
    restart: unless-stopped
  redis-insight:
    profiles:
      - services
    image: "redislabs/redisinsight:latest"
    ports: 
      - 8001:8001
    volumes:
      - ./db/redis-insight:/db
    restart: unless-stopped
  mongodb:
    profiles:
      - db
    image: mongodb/mongodb-community-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - /var/local/docker-volumes/mongo:/data/db
