auth:
  default:
    scheme: jwt
    name: jwt
    options:
      key: $process.env.JWT_SECRET
      verifyOptions: 
        ignoreExpiration: false
        algorithms:
          - HS256
  cookie: 
    ttl: 365 * 24 * 60 * 60 * 1000
    encoding: none
    isSecure: true
    isHttpOnly: true 
    clearInvalid: false
    strictHeader: true