viewConfig:
  template: Pug
  paths: templates

root: /admin

display:
  table:
    fieldsByModel:
      User:
        cols:
          - id
          - email
          - name
          - status
          - logged
          - createdAt
          - updatedAt


redirect:
  login:
    success: "/"
    failed: "/login"