protectedFields:
  - passphrase
  - password

autoFields:
  - createdAt
  - updatedAt
  - id

client: useExternal

auth: passworlesswithemail

modules: 
  - taskManager

imports:
  - { resource: ./config/server/actions.yaml }
  - { resource: ./config/server/routes.yaml }
  - { resource: ./config/server/auth.yaml }
  - { resource: ./config/server/path.yaml }
  - { resource: ./config/front/view.yaml }
  - { resource: ./config/front/fields.yaml }

path:  
  admin: 
    target: "/admin"
    redirect: true
  assets: 
    target: "/assets"
    redirect: true
    folder: "dist/assets"
  lib: 
    target: "/lib"
    redirect: true
    folder: "lib"