byRoute:
  login:
    email: asRequiredEmail
  upload:
    id: asRequiredObjectId
  graphql:
    email: asRequiredEmail
  findOne:
    id: asRequiredObjectId
byModel:
  user:
    email: asRequiredEmail
    role: from$Role
  
payload:
  maxBytes: 209715200,
  output: file,
  parse: true